In [2]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

In [22]:
class BGDRegressor(BaseEstimator, TransformerMixin):
    def __init__(self,eta=0.1,n_iterations=1000,random_state=42):
        self.eta=eta
        self.n_iterations=n_iterations
        self.random_state=random_state
        np.random.seed(self.random_state)
        self.theta=np.random.randn(2,1)
    def fit(self,X,y):
        X_b=np.c_[np.ones((len(X),1)),X]
        m=100
        for iteration in range(self.n_iterations):
            gradients=2/m * X_b.T.dot(X_b.dot(self.theta)-y)
            self.theta=self.theta-self.eta*gradients
        return self
    def predict(self,X):
        X_b=np.c_[np.ones((len(X),1)),X]
        y_predicts=X_b.dots(self.theta)
        return y_predicts
    
    

In [23]:
X=2*np.random.rand(100,1)

In [24]:
y=4+3*X+np.random.randn(100,1)

In [25]:
bat_reg=BGDRegressor()

In [26]:
bat_reg.fit(X,y)

BGDRegressor()

In [27]:
bat_reg.theta

array([[4.20831857],
       [2.79226572]])

In [28]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()

In [30]:
lin_reg.fit(X,y)

LinearRegression()

In [31]:
lin_reg.intercept_

array([4.20831857])

In [32]:
lin_reg.coef_

array([[2.79226572]])