In [2]:
import numpy as np
x=np.array([1,2,4])
print(x)
print(type(x))
m=np.array([[7,8,9],[1,2,3]])
m

[1 2 4]
<class 'numpy.ndarray'>


array([[7, 8, 9],
       [1, 2, 3]])

In [3]:
from numpy import *
t=array([36,4,2])
print(type(t))


<class 'numpy.ndarray'>


In [5]:
m.shape

(2, 3)

In [6]:
n=np.arange(0,30,2)

In [7]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
o=np.linspace(0,4,12)
o

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [10]:
o.resize(3,4)
o

array([[0.        , 0.36363636, 0.72727273, 1.09090909],
       [1.45454545, 1.81818182, 2.18181818, 2.54545455],
       [2.90909091, 3.27272727, 3.63636364, 4.        ]])

In [11]:
np.ones((3,2),int)


array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
np.zeros((2,3),list)


array([[0, 0, 0],
       [0, 0, 0]], dtype=object)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
b=np.eye(4)

In [18]:
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
y=np.array([4,5,6])
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [20]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
p=np.ones([2,3],int)
print(p)
t=np.ones([4,3],int)
print(t)

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
np.vstack([2*p,t])

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [27]:
t.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
m.T

array([[7, 1],
       [8, 2],
       [9, 3]])

In [29]:
m=m.astype('f')
m

array([[7., 8., 9.],
       [1., 2., 3.]], dtype=float32)

In [30]:
m=m.astype('list')
m

TypeError: data type 'list' not understood

In [31]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [32]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [33]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [34]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
r[3,3:6]

array([21, 22, 23])

In [36]:
r[:2,:-4]

array([[0, 1],
       [6, 7]])

In [37]:
r[r>30]

array([31, 32, 33, 34, 35])

In [38]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [39]:
r_copy=r.copy()

In [40]:
r_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [1]:
p=np.ones([3,3],bool)

<IPython.core.display.Javascript object>

In [2]:
p

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
r[r%2!==1]=-1

SyntaxError: invalid syntax (<ipython-input-3-74446ae0e643>, line 1)

In [6]:
r=np.arange(36)
r[r%2==1]=-1
r

<IPython.core.display.Javascript object>

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1,
       34, -1])

In [11]:
e=np.arange(40)
o=np.arange(50)
print(np.intersect1d(e,o))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [16]:
my_array = np.arange(12).reshape(4, 3)
print(my_array)
my_array[:, [2, 0]] = my_array[:, [0, 2]]


<IPython.core.display.Javascript object>

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
my_array[:, [0,1]] = my_array[:, [1,0]]
print(my_array)

[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


In [19]:
my_array[[0,1],:] = my_array[[1,0],:]
print(my_array)

[[ 4  3  5]
 [ 1  0  2]
 [ 7  6  8]
 [10  9 11]]


In [22]:
flip=np.fliplr(my_array)
print(flip)

<IPython.core.display.Javascript object>

[[ 5  3  4]
 [ 2  0  1]
 [ 8  6  7]
 [11  9 10]]


In [23]:
rev = np.flip(my_array, axis=0)
print(rev)

<IPython.core.display.Javascript object>

[[10  9 11]
 [ 7  6  8]
 [ 1  0  2]
 [ 4  3  5]]


In [27]:
t=np.array([36,4,2])
print(np.mean(t))
print(np.median(t))
print(np.std(t))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

14.0


<IPython.core.display.Javascript object>

4.0


<IPython.core.display.Javascript object>

15.57776192739723


In [30]:
three_deci=np.array([5.9888,7.75656,8.9989898,7.52233])
print(np.around(three_deci,decimals=3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[5.989 7.757 8.999 7.522]


In [32]:
a=np.array([0,1,2,3,4,5])
b=np.array([5,4,2,3,1,0])
np.where(a==b)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([2, 3], dtype=int64),)